### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by onebeingmay** [rraadd88/beditor#15]
Hi there,
In the installation instruction you used `pip install beditor` in the virtual environment. This doesn't work. I think it should be `pip3 install beditor`. Thanks

**Comment by rraadd88** [comment]
Hi @onebeingmay,
Yes, that's one way to installation for sure. 
In the docs, first step is installation of python 3.6 environment. So within, 3.6 environment, both commands i.e. `pip install beditor` and `pip3 install beditor` will do the same thing.
Plus, it would't be possible to install beditor in python 2 because of the condition in the [setup](https://github.com/rraadd88/beditor/blob/7946bc139c9e90ce53249fbde7d9b281f5b1a44b/setup.py#L24).
