### ISSUE TITLE
Error during beditor installation on Windows system

### ISSUE THREAD

**Issue by valkm2** [rraadd88/beditor#22]
During the installation of the beditor software, the following error message is shown:

(beditor) C:\>pip install beditor[all]
Collecting beditor[all]
  Downloading beditor-2.0.1.tar.gz (276 kB)
     ---------------------------------------- 276.7/276.7 kB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\valkm2\AppData\Local\Temp\pip-install-vplp5jhc\beditor_1919f043f45a4a99bccd70d50ff5867a\setup.py", line 30, in <module>
          long_description = fh.read()
        File "C:\Users\valkm2\.conda\envs\beditor\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1243: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

How should this be fixed?

**Comment by rraadd88** [comment]
Hi @valkm2, happy to help out. beditor is tested on Linux and it seems that you are using a Windows system (assuming from the \\'s in the paths).

https://github.com/rraadd88/beditor/blob/77779ee3a5df4eb89024b197a38b6bf2831f6dc8/setup.py#L133

Because of the requirements of the dependencies (specifically, cache directories), beditor's compatibility is limited to linux platforms.

As a suggestion, perhaps the use of WSL (Windows Subsystem for Linux) could resolve this issue.
